Repository anastassiavybornova/bike-node-planner, pull requests merged in 2024-11, with the labels that each got.

#56 Refactor matplotlib
  .gitignore
  docs/step06_run_evaluation.md
  scripts/script07.py
  src/plot_func.py
  src/utils.py
  worfklow-bikenodeplanner.qgz
Labels: documentation, enhancement

#60 Script00 further
  config/config-polygon.yml
  docs/screenshots/script00.png
  docs/step06_run_evaluation.md
  scripts-archive/script00.ipynb
  scripts/script00.py
Labels: documentation, enhancement

#61 Anvy 46
  scripts/script01.py
  scripts/script02.py
  scripts/script03.py
  scripts/script04.py
  scripts/script07.py
Labels: enhancement

#62 Script01 polishing
  scripts/script01.py
  scripts/script02.py
  scripts/script08.py
  src/plot_func.py
Labels: bug, enhancement

#64 update qgis-overview screenshot (incl keynote)
  docs/screenshots/qgis-overview.jpeg
  docs/screenshots/qgis-overview.key
  docs/screenshots/qgis-run.png
  docs/step06_run_evaluation.md
Labels: documentation
